// Auto-generated — do not edit
// Icon set: codex (78 icons)

/** All icon names in the "codex" set */
export const names = ["add-background","add-border","align-center","align-justify","align-left","align-right","bold","brackets-vertical","brackets","check","checklist","chevron-down","chevron-left","chevron-right","chevron-up","clipboard","collapse","color","copy","cross","curly-brackets","delimiter","direction-down-right","direction-left-down","direction-right-down","direction-up-right","dot-circle","etc-horisontal","etc-vertical","file","gift","globe","h1","h2","h3","h4","h5","h6","heading","heart","hidden","html","instagram","italic","link","linkedin","list-bulleted","list-numbered","loader","marker","menu-small","menu","picture","play","plus","question","quote","redo","remove-background","replace","save","search","star","stretch","strikethrough","table-with-headings","table-without-headings","table","text","translate","trash","twitter","underline","undo","unlink","user","users-group","warning"] as const

/** Original icon name → PascalCase component name */
export const catalog = {"add-background":"AddBackground","add-border":"AddBorder","align-center":"AlignCenter","align-justify":"AlignJustify","align-left":"AlignLeft","align-right":"AlignRight","bold":"Bold","brackets-vertical":"BracketsVertical","brackets":"Brackets","check":"Check","checklist":"Checklist","chevron-down":"ChevronDown","chevron-left":"ChevronLeft","chevron-right":"ChevronRight","chevron-up":"ChevronUp","clipboard":"Clipboard","collapse":"Collapse","color":"Color","copy":"Copy","cross":"Cross","curly-brackets":"CurlyBrackets","delimiter":"Delimiter","direction-down-right":"DirectionDownRight","direction-left-down":"DirectionLeftDown","direction-right-down":"DirectionRightDown","direction-up-right":"DirectionUpRight","dot-circle":"DotCircle","etc-horisontal":"EtcHorisontal","etc-vertical":"EtcVertical","file":"File","gift":"Gift","globe":"Globe","h1":"H1","h2":"H2","h3":"H3","h4":"H4","h5":"H5","h6":"H6","heading":"Heading","heart":"Heart","hidden":"Hidden","html":"Html","instagram":"Instagram","italic":"Italic","link":"Link","linkedin":"Linkedin","list-bulleted":"ListBulleted","list-numbered":"ListNumbered","loader":"Loader","marker":"Marker","menu-small":"MenuSmall","menu":"Menu","picture":"Picture","play":"Play","plus":"Plus","question":"Question","quote":"Quote","redo":"Redo","remove-background":"RemoveBackground","replace":"Replace","save":"Save","search":"Search","star":"Star","stretch":"Stretch","strikethrough":"Strikethrough","table-with-headings":"TableWithHeadings","table-without-headings":"TableWithoutHeadings","table":"Table","text":"Text","translate":"Translate","trash":"Trash","twitter":"Twitter","underline":"Underline","undo":"Undo","unlink":"Unlink","user":"User","users-group":"UsersGroup","warning":"Warning"} as const

export type IconName = (typeof names)[number]
