// Auto-generated — do not edit
// Icon set: duo-icons (91 icons)

/** All icon names in the "duo-icons" set */
export const names = ["add-circle","airplay","alert-octagon","alert-triangle","align-bottom","align-center","android","app-dots","app","apple","approved","appstore","award","baby-carriage","bank","battery","bell-badge","bell","book-2","book-3","book","bookmark","box-2","box","bread","bridge","briefcase","brush-2","brush","bug","building","bus","cake","calendar","camera-square","camera","campground","candle","car","certificate","chart-pie","check-circle","chip","clapperboard","clipboard","clock","cloud-lightning","cloud-snow","coin-stack","compass","computer-camera-off","computer-camera","confetti","credit-card","currency-euro","dashboard","discount","disk","file","fire","folder-open","folder-upload","g-translate","id-card","info","lamp-2","lamp","location","marker","menu","message-2","message-3","message","moon-2","moon-stars","palette","rocket","settings","shopping-bag","slideshow","smartphone-vibration","smartphone","smartwatch","sun","target","toggle","translation","upload-file","user-card","user","world"] as const

/** Original icon name → PascalCase component name */
export const catalog = {"add-circle":"AddCircle","airplay":"Airplay","alert-octagon":"AlertOctagon","alert-triangle":"AlertTriangle","align-bottom":"AlignBottom","align-center":"AlignCenter","android":"Android","app-dots":"AppDots","app":"App","apple":"Apple","approved":"Approved","appstore":"Appstore","award":"Award","baby-carriage":"BabyCarriage","bank":"Bank","battery":"Battery","bell-badge":"BellBadge","bell":"Bell","book-2":"Book2","book-3":"Book3","book":"Book","bookmark":"Bookmark","box-2":"Box2","box":"Box","bread":"Bread","bridge":"Bridge","briefcase":"Briefcase","brush-2":"Brush2","brush":"Brush","bug":"Bug","building":"Building","bus":"Bus","cake":"Cake","calendar":"Calendar","camera-square":"CameraSquare","camera":"Camera","campground":"Campground","candle":"Candle","car":"Car","certificate":"Certificate","chart-pie":"ChartPie","check-circle":"CheckCircle","chip":"Chip","clapperboard":"Clapperboard","clipboard":"Clipboard","clock":"Clock","cloud-lightning":"CloudLightning","cloud-snow":"CloudSnow","coin-stack":"CoinStack","compass":"Compass","computer-camera-off":"ComputerCameraOff","computer-camera":"ComputerCamera","confetti":"Confetti","credit-card":"CreditCard","currency-euro":"CurrencyEuro","dashboard":"Dashboard","discount":"Discount","disk":"Disk","file":"File","fire":"Fire","folder-open":"FolderOpen","folder-upload":"FolderUpload","g-translate":"GTranslate","id-card":"IdCard","info":"Info","lamp-2":"Lamp2","lamp":"Lamp","location":"Location","marker":"Marker","menu":"Menu","message-2":"Message2","message-3":"Message3","message":"Message","moon-2":"Moon2","moon-stars":"MoonStars","palette":"Palette","rocket":"Rocket","settings":"Settings","shopping-bag":"ShoppingBag","slideshow":"Slideshow","smartphone-vibration":"SmartphoneVibration","smartphone":"Smartphone","smartwatch":"Smartwatch","sun":"Sun","target":"Target","toggle":"Toggle","translation":"Translation","upload-file":"UploadFile","user-card":"UserCard","user":"User","world":"World"} as const

export type IconName = (typeof names)[number]
