// Auto-generated — do not edit
// Icon set: ei (70 icons)

/** All icon names in the "ei" set */
export const names = ["archive","arrow-down","arrow-left","arrow-right","arrow-up","bell","calendar","camera","cart","chart","check","chevron-down","chevron-left","chevron-right","chevron-up","clock","close-o","close","comment","credit-card","envelope","exclamation","external-link","eye","gear","heart","image","like","link","location","lock","minus","navicon","paperclip","pencil","play","plus","pointer","question","redo","refresh","retweet","sc-facebook","sc-github","sc-google-plus","sc-instagram","sc-linkedin","sc-odnoklassniki","sc-pinterest","sc-skype","sc-soundcloud","sc-telegram","sc-tumblr","sc-twitter","sc-vimeo","sc-vk","sc-youtube","search","share-apple","share-google","spinner-2","spinner-3","spinner","star","tag","trash","trophy","undo","unlock","user"] as const

/** Original icon name → PascalCase component name */
export const catalog = {"archive":"Archive","arrow-down":"ArrowDown","arrow-left":"ArrowLeft","arrow-right":"ArrowRight","arrow-up":"ArrowUp","bell":"Bell","calendar":"Calendar","camera":"Camera","cart":"Cart","chart":"Chart","check":"Check","chevron-down":"ChevronDown","chevron-left":"ChevronLeft","chevron-right":"ChevronRight","chevron-up":"ChevronUp","clock":"Clock","close-o":"CloseO","close":"Close","comment":"Comment","credit-card":"CreditCard","envelope":"Envelope","exclamation":"Exclamation","external-link":"ExternalLink","eye":"Eye","gear":"Gear","heart":"Heart","image":"Image","like":"Like","link":"Link","location":"Location","lock":"Lock","minus":"Minus","navicon":"Navicon","paperclip":"Paperclip","pencil":"Pencil","play":"Play","plus":"Plus","pointer":"Pointer","question":"Question","redo":"Redo","refresh":"Refresh","retweet":"Retweet","sc-facebook":"ScFacebook","sc-github":"ScGithub","sc-google-plus":"ScGooglePlus","sc-instagram":"ScInstagram","sc-linkedin":"ScLinkedin","sc-odnoklassniki":"ScOdnoklassniki","sc-pinterest":"ScPinterest","sc-skype":"ScSkype","sc-soundcloud":"ScSoundcloud","sc-telegram":"ScTelegram","sc-tumblr":"ScTumblr","sc-twitter":"ScTwitter","sc-vimeo":"ScVimeo","sc-vk":"ScVk","sc-youtube":"ScYoutube","search":"Search","share-apple":"ShareApple","share-google":"ShareGoogle","spinner-2":"Spinner2","spinner-3":"Spinner3","spinner":"Spinner","star":"Star","tag":"Tag","trash":"Trash","trophy":"Trophy","undo":"Undo","unlock":"Unlock","user":"User"} as const

export type IconName = (typeof names)[number]
