// Auto-generated — do not edit
// Icon set: et (100 icons)

/** All icon names in the "et" set */
export const names = ["adjustments","alarmclock","anchor","aperture","attachments","bargraph","basket","beaker","bike","book-open","briefcase","browser","calendar","camera","caution","chat","circle-compass","clipboard","clock","cloud","compass","desktop","dial","document","documents","download","dribbble","edit","envelope","expand","facebook","flag","focus","gears","genius","gift","global","globe","googleplus","grid","happy","hazardous","heart","hotairballoon","hourglass","key","laptop","layers","lifesaver","lightbulb","linegraph","linkedin","lock","magnifying-glass","map-pin","map","megaphone","mic","mobile","newspaper","notebook","paintbrush","paperclip","pencil","phone","picture","pictures","piechart","presentation","pricetags","printer","profile-female","profile-male","puzzle","quote","recycle","refresh","ribbon","rss","sad","scissors","scope","search","shield","speedometer","strategy","streetsign","tablet","telescope","toolbox","tools-2","tools","traget","trophy","tumblr","twitter","upload","video","wallet","wine"] as const

/** Original icon name → PascalCase component name */
export const catalog = {"adjustments":"Adjustments","alarmclock":"Alarmclock","anchor":"Anchor","aperture":"Aperture","attachments":"Attachments","bargraph":"Bargraph","basket":"Basket","beaker":"Beaker","bike":"Bike","book-open":"BookOpen","briefcase":"Briefcase","browser":"Browser","calendar":"Calendar","camera":"Camera","caution":"Caution","chat":"Chat","circle-compass":"CircleCompass","clipboard":"Clipboard","clock":"Clock","cloud":"Cloud","compass":"Compass","desktop":"Desktop","dial":"Dial","document":"Document","documents":"Documents","download":"Download","dribbble":"Dribbble","edit":"Edit","envelope":"Envelope","expand":"Expand","facebook":"Facebook","flag":"Flag","focus":"Focus","gears":"Gears","genius":"Genius","gift":"Gift","global":"Global","globe":"Globe","googleplus":"Googleplus","grid":"Grid","happy":"Happy","hazardous":"Hazardous","heart":"Heart","hotairballoon":"Hotairballoon","hourglass":"Hourglass","key":"Key","laptop":"Laptop","layers":"Layers","lifesaver":"Lifesaver","lightbulb":"Lightbulb","linegraph":"Linegraph","linkedin":"Linkedin","lock":"Lock","magnifying-glass":"MagnifyingGlass","map-pin":"MapPin","map":"Map","megaphone":"Megaphone","mic":"Mic","mobile":"Mobile","newspaper":"Newspaper","notebook":"Notebook","paintbrush":"Paintbrush","paperclip":"Paperclip","pencil":"Pencil","phone":"Phone","picture":"Picture","pictures":"Pictures","piechart":"Piechart","presentation":"Presentation","pricetags":"Pricetags","printer":"Printer","profile-female":"ProfileFemale","profile-male":"ProfileMale","puzzle":"Puzzle","quote":"Quote","recycle":"Recycle","refresh":"Refresh","ribbon":"Ribbon","rss":"Rss","sad":"Sad","scissors":"Scissors","scope":"Scope","search":"Search","shield":"Shield","speedometer":"Speedometer","strategy":"Strategy","streetsign":"Streetsign","tablet":"Tablet","telescope":"Telescope","toolbox":"Toolbox","tools-2":"Tools2","tools":"Tools","traget":"Traget","trophy":"Trophy","tumblr":"Tumblr","twitter":"Twitter","upload":"Upload","video":"Video","wallet":"Wallet","wine":"Wine"} as const

export type IconName = (typeof names)[number]
