// Auto-generated — do not edit
// Icon set: il (84 icons)

/** All icon names in the "il" set */
export const names = ["add-user","arrow-down","arrow-left","arrow-right","arrow-up","attachment","basket","behance","bell","book","box","brightness","bucket","calendar","camera","card","cart","clock","cloud","cog","comment","compass","contrast","controls","conversation","cup","dashboard","dialog","dribbble","drop","dropbox","ellipsis","email","envelope","eye","facebook","file","flag","folder","github","google-plus","grid","heart","house","image","inbox","instagram","layers","linkedin","location","lock","market","menu","mic","mobile","money","moon","music","notification","paypal","pencil","pie","pin","refresh","ribbon","search","select","small-arrow-down","small-arrow-left","small-arrow-right","small-arrow-up","tablet","tag","thumbs","triangle-down","triangle-up","twitter","unlock","url","user","users","videocamera","world","youtube"] as const

/** Original icon name → PascalCase component name */
export const catalog = {"add-user":"AddUser","arrow-down":"ArrowDown","arrow-left":"ArrowLeft","arrow-right":"ArrowRight","arrow-up":"ArrowUp","attachment":"Attachment","basket":"Basket","behance":"Behance","bell":"Bell","book":"Book","box":"Box","brightness":"Brightness","bucket":"Bucket","calendar":"Calendar","camera":"Camera","card":"Card","cart":"Cart","clock":"Clock","cloud":"Cloud","cog":"Cog","comment":"Comment","compass":"Compass","contrast":"Contrast","controls":"Controls","conversation":"Conversation","cup":"Cup","dashboard":"Dashboard","dialog":"Dialog","dribbble":"Dribbble","drop":"Drop","dropbox":"Dropbox","ellipsis":"Ellipsis","email":"Email","envelope":"Envelope","eye":"Eye","facebook":"Facebook","file":"File","flag":"Flag","folder":"Folder","github":"Github","google-plus":"GooglePlus","grid":"Grid","heart":"Heart","house":"House","image":"Image","inbox":"Inbox","instagram":"Instagram","layers":"Layers","linkedin":"Linkedin","location":"Location","lock":"Lock","market":"Market","menu":"Menu","mic":"Mic","mobile":"Mobile","money":"Money","moon":"Moon","music":"Music","notification":"Notification","paypal":"Paypal","pencil":"Pencil","pie":"Pie","pin":"Pin","refresh":"Refresh","ribbon":"Ribbon","search":"Search","select":"Select","small-arrow-down":"SmallArrowDown","small-arrow-left":"SmallArrowLeft","small-arrow-right":"SmallArrowRight","small-arrow-up":"SmallArrowUp","tablet":"Tablet","tag":"Tag","thumbs":"Thumbs","triangle-down":"TriangleDown","triangle-up":"TriangleUp","twitter":"Twitter","unlock":"Unlock","url":"Url","user":"User","users":"Users","videocamera":"Videocamera","world":"World","youtube":"Youtube"} as const

export type IconName = (typeof names)[number]
